#!/bin/busybox sh

# Install symlinks to busybox commands
/bin/busybox --install

# crucial mountpoints
mount -t proc none /proc
mount -t sysfs none /sys
mount -t bpf bpffs /sys/fs/bpf
mount -n tmpfs /var -t tmpfs -o size=17825792
mount -t tmpfs dev /dev

mknod /dev/console c 5 1
mknod /dev/ttyS0 c 4 64
mknod /dev/ttyS1 c 4 65

# setup console, consider using ptmx?
CIN=/dev/console
COUT=/dev/console
exec <$CIN &>$COUT

mknod /dev/null c 1 3
mknod /dev/gpio c 127 0

mknod /dev/zero c 1 5
mknod /dev/tty c 5 0
mknod /dev/tty0 c 4 0
mknod /dev/tty1 c 4 1
mknod /dev/tty2 c 4 2
mknod /dev/tty3 c 4 3
mknod /dev/tty4 c 4 4
mknod /dev/random c 1 8
mknod /dev/urandom c 1 9
mknod /dev/ptmx c 5 2
mknod /dev/mem c 1 1

mknod /dev/watchdog c 10 130

mknod /dev/mtdblock0 b 31 0
mknod /dev/mtdblock1 b 31 1
mknod /dev/mtdblock2 b 31 2
mknod /dev/mtdblock3 b 31 3
mknod /dev/mtdblock4 b 31 4
mknod /dev/mtdblock5 b 31 5
mknod /dev/mtdblock6 b 31 6
mknod /dev/mtdblock7 b 31 7

mknod /dev/mtd0 c 90 0
mknod /dev/mtd1 c 90 2
mknod /dev/mtd2 c 90 4
mknod /dev/mtd3 c 90 6
mknod /dev/mtd4 c 90 8
mknod /dev/mtd5 c 90 10
mknod /dev/mtd6 c 90 12
mknod /dev/mtd7 c 90 14

mknod /dev/ttyUSB0 c 188 0
mknod /dev/ttyUSB1 c 188 1
mknod /dev/ttyUSB2 c 188 2
mknod /dev/ttyUSB3 c 188 3
mknod /dev/ttyUSB4 c 188 4
mknod /dev/ttyUSB5 c 188 5
mknod /dev/ttyUSB6 c 188 6

mknod /dev/ppp  c 108 0

mknod /dev/i2c-0 c 89 0
mknod /dev/i2c-1 c 89 1
mknod /dev/i2c-2 c 89 2
mknod /dev/i2c-3 c 89 3

mknod /dev/fd0 b 2 0
mknod /dev/fd1 b 2 1
mknod /dev/hda b 3 0
mknod /dev/hda1 b 3 1
mknod /dev/hda2 b 3 2
mknod /dev/hda3 b 3 3
mknod /dev/hda4 b 3 4
mknod /dev/hda5 b 3 5
mknod /dev/hda6 b 3 6
mknod /dev/hda7 b 3 7
mknod /dev/hda8 b 3 8
mknod /dev/hdb b 3 64
mknod /dev/hdb1 b 3 65
mknod /dev/hdb2 b 3 66
mknod /dev/hdb3 b 3 67
mknod /dev/hdb4 b 3 68
mknod /dev/hdb5 b 3 69
mknod /dev/hdb6 b 3 70
mknod /dev/hdb7 b 3 71
mknod /dev/hdb8 b 3 72
mknod /dev/hdc b 22 0
mknod /dev/hdc1 b 22 1
mknod /dev/hdc2 b 22 2
mknod /dev/hdc3 b 22 3
mknod /dev/hdc4 b 22 4
mknod /dev/hdc5 b 22 5
mknod /dev/hdc6 b 22 6
mknod /dev/hdc7 b 22 7
mknod /dev/hdc8 b 22 8
mknod /dev/hdd b 22 64
mknod /dev/hdd1 b 22 65
mknod /dev/hdd2 b 22 66
mknod /dev/hdd3 b 22 67
mknod /dev/hdd4 b 22 68
mknod /dev/hdd5 b 22 69
mknod /dev/hdd6 b 22 70
mknod /dev/hdd7 b 22 71
mknod /dev/hdd8 b 22 72
mknod /dev/sda b 8 0
mknod /dev/sda1 b 8 1
mknod /dev/sda2 b 8 2
mknod /dev/sda3 b 8 3
mknod /dev/sda4 b 8 4
mknod /dev/sda5 b 8 5
mknod /dev/sda6 b 8 6
mknod /dev/sda7 b 8 7
mknod /dev/sda8 b 8 8
mknod /dev/sdb b 8 16
mknod /dev/sdb1 b 8 17
mknod /dev/sdb2 b 8 18
mknod /dev/sdb3 b 8 19
mknod /dev/sdb4 b 8 20
mknod /dev/sdb5 b 8 21
mknod /dev/sdb6 b 8 22
mknod /dev/sdb7 b 8 23
mknod /dev/sdb8 b 8 24
mknod /dev/sr0 b 11 0
mknod /dev/sr1 b 11 1

mkdir /dev/pts /dev/shm

# rest of the mounts
mount none /dev/pts -t devpts
if [ -e /proc/bus/usb ]; then
    mount none /proc/bus/usb -t usbfs
fi

echo "...mounts done"

mkdir -p /var/run /var/tmp /var/log /var/etc /var/etc/persistent /var/lock
echo "...filesystem init done"

# Start network conn
ip link set lo up

echo "...running /sbin/init"
exec /sbin/init

echo "INTERNAL ERROR!!! Cannot run /sbin/init."